### ISSUE TITLE
UDPSink has no async buffer

### ISSUE THREAD

**Issue by aleksei-saharov** [serilog-contrib/Serilog.Sinks.Network#21]
Hello

I have made several benchmarks for your TCPSink and UDPSink with [BenchmarkDotNet](https://benchmarkdotnet.org/articles/overview.html)
I have tested both single-thread and multi-thread applications to write log messages

My results are the following
### TCP (validate single message sending (N = 1)):

Method |  Job | Runtime | N |      Mean |     Error |    StdDev | Ratio | RatioSD |
----------------- |----- |-------- |-- |----------:|----------:|----------:|------:|--------:|
 SendTcpLogsSync |  Clr |     Clr | 1 |  4.302 us | 0.0851 us | 0.0946 us |  1.00 |    0.00 |
 SendTcpLogsSync | Core |    Core | 1 |  3.277 us | 0.0600 us | 0.0561 us |  0.76 |    0.02 |
 SendTcpLogsAsync |  Clr |     Clr | 1 | 12.202 us | 0.2096 us | 0.1960 us |  1.00 |    0.00 |
 SendTcpLogsAsync | Core |    Core | 1 |  9.027 us | 0.1308 us | 0.1224 us |  0.74 |    0.02 |
  
### TCP (validate 100 message sending (N = 100)):

Method |  Job | Runtime |   N |     Mean |    Error |   StdDev | Ratio | RatioSD |
----------------- |----- |-------- |---- |---------:|---------:|---------:|------:|--------:|
 SendTcpLogsSync |  Clr |     Clr | 100 | 418.3 us | 3.261 us | 3.050 us |  1.00 |    0.00 |
 SendTcpLogsSync | Core |    Core | 100 | 316.5 us | 4.051 us | 3.789 us |  0.76 |    0.01 |
 SendTcpLogsAsync |  Clr |     Clr | 100 | 217.7 us | 3.368 us | 3.150 us |  1.00 |    0.00 |
 SendTcpLogsAsync | Core |    Core | 100 | 174.3 us | 2.941 us | 2.751 us |  0.80 |    0.02 |

 ### UDP (validate single message sending (N = 1)):

Method |  Job | Runtime | N |      Mean |     Error |    StdDev | Ratio |
----------------- |----- |-------- |-- |----------:|----------:|----------:|------:|
 SendUdpLogsSync |  Clr |     Clr | 1 |  8.864 us | 0.0839 us | 0.0701 us |  1.00 |
 SendUdpLogsSync | Core |    Core | 1 |  6.750 us | 0.0597 us | 0.0529 us |  0.76 |
 SendUdpLogsAsync |  Clr |     Clr | 1 | 20.914 us | 0.2737 us | 0.2561 us |  1.00 |
 SendUdpLogsAsync | Core |    Core | 1 | 14.905 us | 0.1999 us | 0.1870 us |  0.71 |

### UDP (validate 100 message sending (N = 100)):

Method |  Job | Runtime |   N |     Mean |    Error |   StdDev | Ratio | RatioSD |
----------------- |----- |-------- |---- |---------:|---------:|---------:|------:|--------:|
 SendUdpLogsSync |  Clr |     Clr | 100 | 860.4 us | 9.958 us | 8.827 us |  1.00 |    0.00 |
 SendUdpLogsSync | Core |    Core | 100 | 681.4 us | 3.936 us | 3.489 us |  0.79 |    0.01 |
 SendUdpLogsAsync |  Clr |     Clr | 100 | 277.4 us | 7.458 us | 6.977 us |  1.00 |    0.00 |
 SendUdpLogsAsync | Core |    Core | 100 | 216.3 us | 1.827 us | 1.709 us |  0.78 |    0.02 |

As you can see *Mean* value is two times bigger for UDPSink.

Source code review showed me that the UDPSink send data to socket as soon as evant was emitted
```
void Emit(LogEvent logEvent)
{
    Emitted++;
    var sb = new StringBuilder();

    using (var sw = new StringWriter(sb))
        _formatter.Format(logEvent, sw);

    sb.Replace("RenderedMessage", "message");

    _socket.Send(Encoding.UTF8.GetBytes(sb.ToString()));
}
```

### Quesions:
1. Is there any reasons to skip buffering for UDPSink?
2. Is it possible to add a async buffer as well as it done for TCPSink?

**Comment by pauldambra** [comment]
very old issue with no PR
