### ISSUE TITLE
TcpSocketWriter maxQueueSize is not configurable

### ISSUE THREAD

**Issue by aleksei-saharov** [serilog-contrib/Serilog.Sinks.Network#22]
**Issue:**
TCPSink constructor does not use maxQueueSize of TcpSocketWriter.
```
public TCPSink(IPAddress ipAddress, int port, ITextFormatter formatter)
{
    _socketWriter = new TcpSocketWriter(new Uri($"tcp://{ipAddress}:{port}"));
    _formatter = formatter;
}
```
In our application we want to extend a queue size.

**Request:**
1. Let's add maxQueueSize optional parameter for TCPSink constructor
2. Let's add maxQueueSize to NetworkLoggerConfigurationExtensions extension methods

**Comment by pauldambra** [comment]
very old issue with no PR
