### ISSUE TITLE
TCP Connection aborted and throws IOException

### ISSUE THREAD

**Issue by tafs7** [serilog-contrib/Serilog.Sinks.Network#23]
I keep seeing the following exception when my app uses the TCP network sink.  On some desktops, the connection works, but throws this intermittent, however on one server where we run the app, this always occurs and we're never able to send the logs.

We are connecting to a Logstash endpoint via TCP.

```
System.IO.IOException: Unable to write data to the transport connection: An established connection was aborted by the software in your host machine. ---> System.Net.Sockets.SocketException: An established connection was aborted by the software in your host machine
   at System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   at System.Net.Sockets.NetworkStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at System.IO.Stream.<>c.<BeginEndWriteAsync>b__53_0(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
   at System.IO.Stream.BeginEndWriteAsync(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.IO.Stream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count)
   at Serilog.Sinks.Network.Sinks.TCP.TcpSocketWriter.<>c__DisplayClass8_1.<<-ctor>b__1>d.MoveNext()
```

**Comment by tafs7** [comment]
no comments from anyone?  Bueller?

**Comment by tafs7** [comment]
I have a suspicion.  My app opens a TCP connection (AMQP) to RabbitMQ.  I noticed that app logs do go out the TCP connection when I start the up, but at the point during start up when I open the AMQP connection on TCP, it stops sending logs out via TCP.  I wonder if there's a conflict where the sink's TCP socket is getting closed because the AMQP connection is opening another one up.

**Comment by pauldambra** [comment]
So sorry not to reply! I've not had any email notifications about this issue.

When I've had serilog problems it's always been useful to use https://github.com/serilog/serilog/wiki/Debugging-and-Diagnostics

e.g. `Serilog.Debugging.SelfLog.Enable(msg => Debug.WriteLine(msg));` at app startup.

**Comment by tafs7** [comment]
@pauldambra I have that enabled, but it doesn't self-log anything.  I did repro it on a separate console app.

I created a brand new console app, added this sink, and ran and saw it sending some log lines as expected.  Then I added a reference to the RabbitMQ client lib, and opened a connection to both publish a message - since publishing doesn't hang on to a socket for long, I didn't see the issue.

Then I added code to subscribe to a queue, which essentially opens a socket and stays on it waiting for messages to consume. Once I ran that, I started seeing the Serilog TCP logger connection throw the exception above.

Another data point is that on another app (WPF) where I encounter this error, we don't use Rabbit, but we do have an HttpClient as well as a persistent SQL connection (TCP) which remains open while the app is running.

My last test will be to clone this repo and add the project reference directly to my test console app, so I can step thru and debug more closely the code in this sink.

Otherwise I will need to look at a different sink option like HTTP to send my logs out to Logstash.

Let me know if you have any thoughts.

**Comment by pauldambra** [comment]
Are they all TCP connections on the same port? Or...

**Comment by tafs7** [comment]
well....the RabbitMQ and SQL connections are TCP to different remote servers, and definitely not to same port :)

**Comment by pauldambra** [comment]
Fascinating... I've used this on Linux and Windows with other TCP connections alongside

(although admittedly not since the .Net core update but others contributed that and I'd guess they had other TCP connections)

More than happy to look at a reproduction of the problem to see if I can help understand...

**Comment by tafs7** [comment]
I'm doing some further investigations of my own, but feel free to repro if you'd like.  I'll post any significant findings here.  thx!

**Comment by tafs7** [comment]
Looks like this line is where the exception is thrown and then caught and logged: https://github.com/pauldambra/Serilog.Sinks.Network/blob/8fcb0cefae6c5c54536716b7bb254fb0328226ad/Serilog.Sinks.Network/Sinks/TCP/TCPSocketWriter.cs#L137

**Comment by tafs7** [comment]
I was also able to repro by opening up a SQL database connection and leaving it open, then put a thread.sleep of 60s, then before closing the connection, I tried to write to log, and BOOM.

**Comment by tafs7** [comment]
Oh, and to add to this test, I decided to use .NET 4.7.2 Framework (not Core)

**Comment by tafs7** [comment]
More test results using .net framework console app, and opening a DB connection prior to sending several log entries.  Seems like they work if sent immediately after...but if you wait a bit (e.g. 30 or 60 sec) after the DB connection was opened, we start seeing the errors when trying logs to TCP sink.

![image](https://user-images.githubusercontent.com/671795/57051880-5bcbb500-6c49-11e9-915e-9d2881fdc8fe.png)

**Comment by okman523** [comment]
I also encountered this problem in the .net core project? Is there any solution?

**Comment by tafs7** [comment]
@okman523 I have not been about to resolve it.  I suspect it's some concurrency issue with the `TcpSocketWriter`.

I'm considering switching over to another sink, likely the RabbitMQ one, since I'll already be connecting to RabbitMQ for messaging.

**Comment by pauldambra** [comment]
I'm sorry to hear that.

Struggling to think what this could be. I've used it under load alongside other TCP connections. Not sure where to go next

I wonder if the DB driver is putting load on the threadpool?! Casting about for an idea though

**Comment by pauldambra** [comment]
Can I check @tafs7 - the logger should reconnect to TCP after a small delay. Does it not reconnect?

**Comment by tafs7** [comment]
@pauldambra I have 2 apps using this sink:
1) connects to SQL Server and also makes HTTP requests using HttpClient.  
2) connects to RabbitMQ only.

The first app seems to reconnect after a delay as you suggest, and will eventually recover logging. (see screenshot)

However, the 2nd one never recovers, once it connects to RabbitMQ.  It uses the Pivotal RabbitMQ.Client nuget package.

![image](https://user-images.githubusercontent.com/671795/59471739-ab350180-8e01-11e9-8925-7570080ac04c.png)

**Comment by pauldambra** [comment]
Really intriguing. I've used it alongside PostgreSQL and EventStore. But I know there are other folk using it so... I've pushed a very speculative point release that should capture more detail from SocketExceptions but I can only fake them here so it's very hand-wavy :)

Is your setup in docker? I'm wondering about writing a test that logs in a loop, starts SQL in docker, and then asserts it can continue logging.

**Comment by tafs7** [comment]
@pauldambra I don't think the SQL connection is going to repro the issue as quickly as a connection RabbitMQ.

No, my setup is a console app - technically a Windows service.  But the RabbitMQ broker is on docker.

For your testing, you could just run a rabbitmq docker image using a compose like this: https://github.com/micahhausler/rabbitmq-compose/blob/master/docker-compose.yml

**Comment by tafs7** [comment]
@pauldambra @okman523 have you guys had a chance to test this any further and dig into why this may be happening?

Per my last comment, if you create an small app which sets up the logging, then proceeds to open up a TCP connection to a RabbitMQ broker (I use the RabbitMQ .NET client nuget pkg), it will forcibly close any TCP sockets that the logging sink tries to open.

**Comment by tafs7** [comment]
@pauldambra i see you added some tests and new code, but just wanted to check if you or anyone else were able to repro this and had any idea why this happens.

**Comment by pauldambra** [comment]
All I added was some speculative improvement to logging in the hope you or someone else could report something more concrete.

I've run this alongside TCP connections before so I'm guessing something in your environment (or changes to .Net or something) has changed out under us and better logging would help...

Can you share your code that you used to reproduce @tafs7 ?

**Comment by tafs7** [comment]
@pauldambra Litterally any app that either opens a DB connection, uses an HTTP Client, or connects to a RabbitMQ broker via TCP, after having had the logger configured, will exhibit this behavior.

**Comment by pauldambra** [comment]
very old issue with no reproduction
