### ISSUE TITLE
how to output message about an object to TCP sink in Json format

### ISSUE THREAD

**Issue by Nitin5acc** [serilog-contrib/Serilog.Sinks.Network#28]
Hello,
I am using Serilog TCP sink like this - 
```
//Object
var nitin = new Employee {Name = "Nitin", Ssn = "112"};
 //Serilog Client
                var ip = IPAddress.Parse(ServerIp);
                .WriteTo.TCPSink(ip, PortNo, new JsonFormatter())
                    .CreateLogger();
 log.Information("{@nitin}",nitin);
```
the output is -
`{"host":"10.208.11.71","Timestamp":"2019-12-06T12:04:45.5160298-06:00","MessageTemplate":"{@nitin}","timestamp":"2019-12-06T18:04:45.536092500Z","Properties":{"nitin":{"Ssn":"112","_typeTag":"Employee","Name":"Nitin"}},"Level":"Information"}`

which is not in json format I want . How to I change the above message in Json format to -

```
{"timestamp":"2019-12-06T09:45:33.7410418-06:00","level":"Information","message":{
"nitin":{"Ssn":"112","Name":"Nitin"}
}}
```

**Comment by pauldambra** [comment]
I appreciate this comment is very late :)

https://github.com/serilog-contrib/Serilog.Sinks.Network#json-structure-logstashjsonformatter

The logger purposefully writes a string to the message field to fit in with ELK conventions.
